Update ci.yml norm

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -48,4 +48,13 @@ jobs:
         pip3 install norminette
 
     - name: Run Norminette
-      run: make norm
+      run: |
+        make norm > output.txt
+        cat output.txt
+        ERROR_COUNT=$(grep -c 'Error!' output.txt)
+        if [ "$ERROR_COUNT" -ne 0 ]; then
+          echo "Norminette found errors. Failing the job."
+          exit 1
+        else
+          echo "Norminette found no errors."
+        fi
